import { chromium, type Browser } from "@playwright/test";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { randomBytes } from "node:crypto";
import { mkdir } from "node:fs/promises";
import { SignJWT } from "jose";
import mongoose from "mongoose";
import { allPermissions } from "../lib/permissions";
import { createTestQuestion, normalizeTestSettings } from "../lib/form-test";
import { normalizeFormSettings } from "../lib/form-layout";

async function main() {
  const database = `aperture_grading_test_${Date.now()}`;
  const uri = `mongodb://127.0.0.1:27017/${database}`;
  process.env.MONGODB_URI = uri;
  const secret = randomBytes(32).toString("hex");
  const baseURL = "http://localhost:3188";
  const { Role, User, FormDefinition, FormSubmission, TestAttempt } = await import("../lib/models");
  await mongoose.connect(uri);
  const role = await Role.create({ name: "Test admin", slug: "administrator", kind: "management", permissions: allPermissions });
  const admin = await User.create({ email: "admin@example.invalid", name: "Instructor", passwordHash: "unused", roleIds: [role._id], membershipStatus: "active", emailVerifiedAt: new Date() });
  const taker = await User.create({ email: "taker@example.invalid", firstName: "Test", lastName: "Taker", passwordHash: "unused", roleIds: [], membershipStatus: "active", emailVerifiedAt: new Date() });
  const choice = createTestQuestion("radio");
  choice.variants[0].block.label = "Choose yes";
  choice.variants[0].block.options = ["Yes", "No"];
  choice.variants[0].key.correctOptions = ["Yes"];
  choice.variants[0].block.mediaUrl = "https://question.example.invalid/diagram.svg";
  choice.variants[0].block.width = 30;
  const essay = createTestQuestion("longText");
  essay.variants[0].block.label = "Explain your answer"; essay.points = 3;
  const definition = await FormDefinition.create({ title: "Review test", slug: "review-test", kind: "test", status: "published", settings: normalizeFormSettings({}), test: normalizeTestSettings({ questions: [choice, essay], requireReview: true, passMark: 75, attemptLimit: 3 }) });
  const child = spawn(process.execPath, ["node_modules/next/dist/bin/next", "start", "-p", "3188"], { env: { ...process.env, MONGODB_URI: uri, SESSION_SECRET: secret, SEED_ADMIN_EMAIL: "", SEED_ADMIN_PASSWORD: "" }, stdio: ["ignore", "pipe", "pipe"], windowsHide: true });
  let logs = "";
  child.stdout?.on("data", chunk => { logs += chunk; }); child.stderr?.on("data", chunk => { logs += chunk; });
  let browser: Browser | undefined;
  try {
    for (let i = 0; i < 60; i++) { try { await fetch(`${baseURL}/login`); break; } catch { await new Promise(resolve => setTimeout(resolve, 500)); } }
    browser = await chromium.launch({ headless: true });
    async function contextFor(user: any) {
      const context = await browser!.newContext();
      await context.route("https://question.example.invalid/diagram.svg", route => route.fulfill({ contentType: "image/svg+xml", body: '<svg xmlns="http://www.w3.org/2000/svg" width="600" height="300"><rect width="600" height="300" fill="blue" /></svg>' }));
      const token = await new SignJWT({ userId: String(user._id), email: user.email, name: user.name || "Test Taker", mustChangePassword: false }).setProtectedHeader({ alg: "HS256" }).setIssuedAt().setExpirationTime("1h").sign(new TextEncoder().encode(secret));
      await context.addCookies([{ name: "aperture_session", value: token, url: baseURL }]);
      return context;
    }
    const staff = await contextFor(admin); const member = await contextFor(taker);
    const editor = await staff.newPage(); const page = await member.newPage();
    await editor.goto(`${baseURL}/admin/forms/${definition._id}/test`);
    assert.equal(await editor.getByRole("tab").count(), 6);
    await editor.getByRole("tab", { name: "Answer key", exact: true }).click();
    assert.equal(await editor.getByRole("tabpanel", { name: "Answer key" }).getByText("Radio group").count(), 1);
    await mkdir("backups/test-artifacts", { recursive: true });
    await editor.screenshot({ path: "backups/test-artifacts/test-answer-key.png", fullPage: true });
    await editor.getByRole("tab", { name: "How it is given", exact: true }).click();
    assert.equal(await editor.getByLabel("Hold results for instructor review").isChecked(), true);
    await editor.getByLabel("Hold results for instructor review").uncheck();
    await editor.getByRole("tab", { name: "Questions", exact: true }).click();
    const width = editor.getByLabel("Maximum image width (pixels)");
    assert.equal(await width.inputValue(), "480");
    await width.fill("240");
    await editor.getByLabel("Instructor graded", { exact: true }).check();
    assert.equal(await editor.getByText("Accepted answers (one per line)", { exact: true }).isVisible(), false);
    await editor.getByLabel("Instructions", { exact: true }).isVisible().then(visible => assert.equal(visible, false));
    const saved = editor.waitForResponse(response => response.request().method() === "POST" && response.url().includes("/admin/forms/"));
    await editor.getByRole("button", { name: "Save", exact: true }).click();
    await saved;
    const savedSettings = (await FormDefinition.findById(definition._id).lean<any>()).test;
    assert.equal(savedSettings.requireReview, false);
    assert.equal(savedSettings.questions[1].variants[0].instructorGraded, true);
    assert.equal(savedSettings.questions[0].variants[0].block.imageMaxWidth, 240);
    await page.goto(`${baseURL}/test/review-test`);
    await page.locator(".form-question-image").evaluate((image: HTMLImageElement) => image.decode());
    assert.equal(Math.round((await page.locator(".form-question-image").boundingBox())!.width), 240);
    await page.getByLabel("Yes", { exact: true }).check();
    await page.getByLabel("Explain your answer", { exact: false }).fill("My explanation");
    const submission = page.waitForResponse(response => response.url().endsWith("/api/forms/submit") && response.request().method() === "POST");
    await page.getByRole("button", { name: "Submit", exact: true }).click();
    const submitted = await (await submission).json();
    assert.equal(submitted.grade, undefined);
    await page.getByText("Results will be shared on your dashboard after it is graded.", { exact: true }).waitFor();
    const attempt = await TestAttempt.findOne({ userId: String(taker._id) }).lean<any>();
    assert.equal(attempt.gradingStatus, "pending");
    assert.equal(attempt.grade.questions.length, 2);
    await page.goto(`${baseURL}/dashboard`);
    await page.getByRole("cell", { name: "Pending", exact: true }).waitFor();
    assert.equal(await page.getByText("25%", { exact: true }).count(), 0);
    const denied = await member.request.patch(`${baseURL}/api/admin/tests/results/${attempt._id}`, { data: { awards: [1, 3], version: new Date(attempt.updatedAt).toISOString() } });
    assert.equal(denied.status(), 403);
    const invalid = await staff.request.patch(`${baseURL}/api/admin/tests/results/${attempt._id}`, { data: { awards: [1, 100], version: new Date(attempt.updatedAt).toISOString() } });
    assert.equal(invalid.status(), 400);
    await editor.goto(`${baseURL}/admin/tests/results/${definition._id}`);
    await editor.getByRole("button", { name: "Grade", exact: true }).click();
    await editor.getByLabel("Points for question 2", { exact: true }).fill("2");
    await editor.screenshot({ path: "backups/test-artifacts/test-grading.png", fullPage: true });
    await editor.getByRole("button", { name: "Release grade", exact: true }).click();
    await editor.getByRole("dialog").getByText("75%", { exact: true }).waitFor();
    const stale = await staff.request.patch(`${baseURL}/api/admin/tests/results/${attempt._id}`, { data: { awards: [0, 0], version: new Date(attempt.updatedAt).toISOString() } });
    assert.equal(stale.status(), 409);
    await page.reload();
    await page.getByRole("cell", { name: "75% — Pass", exact: true }).waitFor();
    await page.screenshot({ path: "backups/test-artifacts/test-results-dashboard.png", fullPage: true });
    // Retakes remain individual attempts, and cannot conceal an earlier grade.
    const body = { formId: String(definition._id), sitting: [choice, essay].map(q => ({ questionId: q.id, variantId: q.variants[0].id })), fields: [choice, essay].map(q => ({ id: q.variants[0].block.id, value: "No" })) };
    const retake = await member.request.post(`${baseURL}/api/forms/submit`, { data: body });
    assert.equal(retake.status(), 200);
    await page.reload();
    await page.getByRole("cell", { name: "Pending", exact: true }).waitFor();
    await page.getByRole("cell", { name: "75% — Pass", exact: true }).waitFor();
    assert.equal(await TestAttempt.countDocuments(), 2);
    assert.equal((await FormSubmission.findOne({ userId: String(taker._id) }).lean<any>()).attempts, 2);
    const second = await TestAttempt.findOne({ gradingStatus: "pending" }).lean<any>();
    const failed = await staff.request.patch(`${baseURL}/api/admin/tests/results/${second._id}`, { data: { awards: [0, 1], version: new Date(second.updatedAt).toISOString() } });
    assert.equal(failed.status(), 200);
    await page.reload();
    await page.getByRole("cell", { name: "25% — Fail", exact: true }).waitFor();
    assert.equal((await FormSubmission.findOne({ userId: String(taker._id) }).lean<any>()).grade.percent, 75);
    await FormDefinition.updateOne({ _id: definition._id }, { $set: { "test.requireReview": false, "test.questions.1.variants.0.instructorGraded": false } });
    const immediate = await member.request.post(`${baseURL}/api/forms/submit`, { data: body });
    const immediateResult = await immediate.json();
    assert.equal(immediateResult.pendingReview, false);
    assert.equal(immediateResult.grade.percent, 0);
    const exceeded = await member.request.post(`${baseURL}/api/forms/submit`, { data: body });
    assert.equal(exceeded.status(), 403);
    const deleted = await staff.request.delete(`${baseURL}/api/admin/tests/results/${second._id}`);
    assert.equal(deleted.status(), 200);
    assert.equal(await TestAttempt.countDocuments(), 2);
    const privatePage = await staff.newPage(); await privatePage.goto(`${baseURL}/dashboard`);
    assert.equal(await privatePage.getByRole("heading", { name: "Test results", exact: true }).count(), 0);
    console.log("Grading browser checks passed: tabs, answer key, held submission, dashboard privacy, grading permissions, invalid points, release, stale grading, and retakes.");
  } catch (error) { console.error(logs.slice(-5000)); throw error; }
  finally { await browser?.close(); child.kill(); if (mongoose.connection.name === database && database.startsWith("aperture_grading_test_")) await mongoose.connection.dropDatabase(); await mongoose.disconnect(); }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
